#RequireAdmin
Run("setup.exe")
WinWait("Cambridge Advanced Learner's Dictionary - 3rd Edition" , "Welcome to the CALD3 Setup Wizard")
ControlSend("Cambridge Advanced Learner's Dictionary - 3rd Edition" , "&Next >" , "Button2" , "!n")
Sleep(400)
WinWait("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "License Agreement")
ControlSend("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "I &Agree" , "Button2" , "!a")
Sleep(400)
WinWait("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "Choose Components")
ControlSend("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "&Next >" , "Button2" , "!n")
Sleep(400)
WinWait("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "Choose Install Location")
ControlSend("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "&Install" , "Button2" , "!i")
Sleep(400)
WinWait("Cambridge Advanced Learner's Dictionary - 3rd Edition" , "&Yes")
ControlSend("Cambridge Advanced Learner's Dictionary - 3rd Edition" , "&Yes" , "Button1" , "!y")
Sleep(400)
WinWait("QUICKfind v1.1 Setup " , "Choose Install Location")
ControlSend("QUICKfind v1.1 Setup " , "&Install" , "Button2" , "!i")
Sleep(400)
WinWait("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "&Finish")
ControlSend("Cambridge Advanced Learner's Dictionary - 3rd Edition " , "&Finish" , "Button2" , "!f")
Sleep(400)
WinWait("Cambridge Advanced Learner's Dictionary - 3rd Edition" , "&Yes")
ControlSend("Cambridge Advanced Learner's Dictionary - 3rd Edition" , "&No" , "Button2" , "!n")
Sleep(400)
Exit